config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#welcome'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    resources :recipes
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, presence: true
  validates :yummly_id, presence: true, uniqueness: true
  validates :recipe_url, presence: true, uniqueness: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, 
            uniqueness: {case_sensitive: false}, length: {maximum: 255}

  validates :password, length: {minimum: 6}
  has_secure_password
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def create
    puts params
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      render status: 200, nothing: true
    else
      render status: 500, nothing: true
    end
  end

  def destroy
    @recipe = Recipe.find_by_yummly_id(params[:id])
    @recipe.destroy
    render nothing: true
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :yummly_id, :recipe_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', test: "i'm a test"
    end
  end 

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
    if logged_in?
      redirect_to current_user
    else
      redirect_to '/users/new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Staple</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <div class="errorsFlash">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><span class="errorToken">*</span><%= message %></div>
    <% end %>
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<div class="signUpErrors">
<% if @user.errors.any? %>
  <span class='errorToken'>*</span><%=@user.errors.full_messages[0]%>
<% end %>
</div>

app/views/static_pages/welcome.html.erb
<p> Welcome to staple!</p>

app/views/users/new.html.erb
<%= stylesheet_link_tag "signup-login" %>
<div id="background-blur"></div>
<div class="signup_wrapper">
  <h1 id="home_title">Staple</h1>
  <h2 id="home_subtitle">An easy way to create grocery lists.</h2>
  <div class="form-wrapper">
  <%= form_for(@user, html: {class: "user-form"}) do |f| %>
    <%= f.text_field :name, placeholder: "Name", class: "form-input" %> <br>

    <%= f.email_field :email, placeholder: "Email", class: "form-input" %> <br>

    <%= f.password_field :password, placeholder: "Password", class: "form-input" %> <br>

    <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-input" %> <br>

    <%= f.submit "Sign up", class: "submit-button" %>
    <p> Already signed up? Login in <%=link_to "here", login_path%> </p>
  <% end%>
  <%= render 'shared/error_messages' %>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "user-profile" %>

<%= javascript_tag do%>
  userID = <%= current_user.id %>;
<%end%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<nav> 
  <div id="pageTitle"> Staple </div>
  <div id="logoutTitle"> <%= link_to 'logout', logout_path, :method => :delete%>
</div>
</nav>

<div class="sideBar">
  <div class="selectedRecipesTitle">My Recipes</div>
  <div class="selectedRecipes">
    <% current_user.recipes.each do |recipe| %>
      <div data-recipe-url=<%=recipe.recipe_url%> data-id=<%=recipe.yummly_id%> class='selectedRecipeView'> 
        <div class="selectedRecipeName">
          <%=recipe.name%>
        </div>
        <div class="deleteRecipe">x</div>
      </div>
    <% end %>
  </div>
  <div class="makeGroceryList">Create Grocery List</div>
</div>


<div class="mainPage">
  <div class="search">
    <input type="text" name="search", class="search-input" placeholder="Search recipes">
    <div class="search-button"></div>
  </div>
  <div class="recipeGrid"></div>
</div>